# Generated by Django 5.1.2 on 2024-10-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow_rate', models.FloatField()),
                ('cumulative_flow_rate', models.FloatField()),
                ('water_production', models.FloatField()),
                ('condensate_production', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionRecord',
        ),
        migrations.AddField(
            model_name='productiondata',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='production_data.well'),
        ),
        migrations.AlterUniqueTogether(
            name='productiondata',
            unique_together={('well', 'date')},
        ),
    ]
