# Generated by Django 5.1.2 on 2024-11-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0002_productiondata_well_delete_productionrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, help_text='Area in square kilometers', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='gas_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='production_data.gasfield'),
            preserve_default=False,
        ),
    ]
